//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.27 at 04:00:05 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://abis.be/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.abis.exercise.ws.model;
